---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/aavn-ct-workshop/centralized-configuration-challenge.git
    app.quarkus.io/build-timestamp: 2021-07-07 - 11:32:25 +0000
    app.quarkus.io/commit-id: 8c9cf40f64ec2dbea92544da872a90ed69989973
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/version: 1.0.0
  name: payment-service
  namespace: foody-clone
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/aavn-ct-workshop/centralized-configuration-challenge.git
    app.quarkus.io/build-timestamp: 2021-07-07 - 11:32:25 +0000
    app.quarkus.io/commit-id: 8c9cf40f64ec2dbea92544da872a90ed69989973
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: payment-service
  name: payment-service
  namespace: foody-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: payment-service
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/aavn-ct-workshop/centralized-configuration-challenge.git
        app.quarkus.io/build-timestamp: 2021-07-07 - 11:32:25 +0000
        app.quarkus.io/commit-id: 8c9cf40f64ec2dbea92544da872a90ed69989973
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: payment-service
      namespace: foody-clone
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: payment-service:1.0.0
        imagePullPolicy: IfNotPresent
        name: payment-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 64Mi
